swagger:
  enable: true
environment:
  name: dev
spring:
  datasource:
    url: jdbc:mysql://119.3.8.251:33066/fun_pms_energy_monitor_test2?useSSL=false&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: fun_develop_test2
    password: TYVLHgauIZMs
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080


