spring:
  profiles:
    active: ${ENVIRONMENT_TYPE:dev}
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    default-property-inclusion: non_null


logging:
  level:
    com.sce.ifun.pms.energy.dao: info

mybatis:
  type-aliases-package: com.sce.ifun.pms.energy.dao.domain
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql





